# Generated by Django 4.1.3 on 2022-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="inscriptionrequest",
            name="trainings",
            field=models.ManyToManyField(
                related_name="requests", to="inscriptions.academictraining"
            ),
        ),
    ]
